import { ReactNode } from "react";
import styles from './PrintLayout.module.css';
import { DownloadIcon, PrinterIcon } from "lucide-react";

interface Props {
  documentType: string;
  documentId: string;
  title: string;
  children: ReactNode;
  printCount?: number;
  downloadUrl?: string;
}
export default function PrintLayout({ documentType, documentId, title, children, printCount = 0, downloadUrl = '' }: Props) {

  function handlePrint(): void {
    requestAnimationFrame(() => window.print())
  }

  function handleDownload(): void {
    if (downloadUrl) window.open(downloadUrl, '_blank');
  }

  return (
    <>
      <div className={styles.toolbar}>
        <div className={styles.toolbarLeft}>
          <button className={styles.backBtn} onClick={() => window.history.back()}>
            ← Back
          </button>
          <div className={styles.docInfo}>
            <span className={styles.docType}>{documentType}</span>
            <span className={styles.docId}>{documentId}</span>
          </div>

          {/* Printed Count Badge */}
          <span className={styles.printCount} title="Times printed">
            Printed {printCount} Times {printCount > 1 ? 's' : ''}
          </span>
        </div>

        <div className={styles.toolbarRight}>
          <button className={styles.downloadBtn} onClick={handleDownload}>
            <DownloadIcon /> Download PDF
          </button>
          <button className={styles.printBtn} onClick={handlePrint}>
            <PrinterIcon /> Print
          </button>
        </div>
      </div>

      {/* ===== Printable Page Container ===== */}
      <div className={styles.page}>

        {/* Header */}
        <div className={styles.pageHeader}>
          <div className={styles.hospitalInfo}>
            <img
              src="/Dashboard/img/brand/favicon.png"
              alt="Valex"
              className={styles.logo}
            />
            <div>
              <h1 className={styles.hospitalName}>Valex Hospital</h1>
              <p className={styles.hospitalSub}>Hospital Management System</p>
            </div>
          </div>

          <div className={styles.documentInfo}>
            <h2 className={styles.documentTitle}>{title}</h2>
            <p className={styles.documentMeta}>
              Document #{documentId}
            </p>
          </div>
        </div>

        <hr className={styles.divider} />

        {/* Document Body Slot Area */}
        <div className={styles.content}>
          <div style={{ padding: '1rem 0', lineHeight: '1.6' }}>
            {children}
          </div>
        </div>

        {/* Printable Footer */}
        <div className={styles.pageFooter}>
          <div className={styles.signatures}>
            <div className={styles.signature}>
              <div className={styles.signatureLine} />
              <span>Authorized Signature</span>
            </div>
            <div className={styles.signature}>
              <div className={styles.signatureLine} />
              <span>Recipient Signature</span>
            </div>
          </div>
          <p className={styles.footerNote}>
            Generated by Valex HMS | {new Date().toLocaleString()}
          </p>
        </div>

      </div>
    </>
  );


}